Repository 5-SpringSpring/Pet-Partner, pull requests merged in 2024-05, with the labels that each got.

#2 Feed 도메인 구현
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/entity/Comment.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/controller/FeedController.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/dto/CreateFeedRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/dto/FeedResponse.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/dto/UpdateFeedRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/entity/Feed.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/repository/FeedRepository.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/service/FeedService.kt
  src/main/kotlin/team/springpsring/petpartner/infra/swagger/SwaggerConfig.kt
  src/main/resources/application.yml
Labels: ✨Feature

#7 Comment domain 작성
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/controller/CommentController.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/dto/CommentResponse.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/dto/CreateCommentRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/dto/UpdateCommentRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/entity/Comment.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/repository/CommentRepository.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/service/CommentService.kt
Labels: ✨Feature

#12 feed와 comment 연결작업
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/service/CommentService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/entity/Feed.kt
Labels: ✨Feature

#13 로그아웃 기능
  src/main/kotlin/team/springpsring/petpartner/domain/user/controller/UserController.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/dto/GetUserInfoRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/dto/UpdateUserPasswordRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/dto/UserResponse.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/entity/User.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/loginUser/entity/LoginUser.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/loginUser/repository/LoginUserRepository.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/loginUser/service/LoginUserService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/service/UserService.kt
Labels: ✨Feature

#17 엔티티 관련 버그 수정
  src/main/kotlin/team/springpsring/petpartner/domain/feed/dto/FeedResponse.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/entity/Feed.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/service/FeedService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/love/dto/CreateLoveRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/love/dto/LoveResponse.kt
  src/main/kotlin/team/springpsring/petpartner/domain/love/entity/Love.kt
  src/main/kotlin/team/springpsring/petpartner/domain/love/service/LoveService.kt
Labels: 🐛Bug

#18 Feat#16 loginTabe_login_logout로직 변경
  src/main/kotlin/team/springpsring/petpartner/domain/user/controller/UserController.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/loginUser/repository/LoginUserRepository.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/loginUser/service/LoginUserService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/service/UserService.kt
Labels: ♻Refactor

#21 Feed와 사용자 연결
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/dto/CommentResponse.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/dto/CreateCommentRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/entity/Comment.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/service/CommentService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/controller/FeedController.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/dto/CreateFeedRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/dto/FeedResponse.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/dto/UpdateFeedRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/entity/CategoryType.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/entity/Feed.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/repository/FeedRepository.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/service/FeedService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/love/controller/LoveController.kt
  src/main/kotlin/team/springpsring/petpartner/domain/love/dto/CreateLoveRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/love/service/LoveService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/dto/UpdateUserPasswordRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/loginUser/repository/LoginUserRepository.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/loginUser/service/LoginUserService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/service/UserService.kt
Labels: ✨Feature

#23 Feat : ValidEmailService 작성 및 연결
  build.gradle.kts
  src/main/kotlin/team/springpsring/petpartner/PetPartnerApplication.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/service/UserService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/validemail/controller/CheckController.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/validemail/dto/CheckPassCodeRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/validemail/dto/SendPassCodeRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/validemail/service/ValidEmailService.kt
  src/main/resources/application.yml
Labels: ✨Feature

#25 전체 코드 refactoring
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/controller/CommentController.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/dto/CommentRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/dto/UpdateCommentRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/entity/Comment.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/repository/CommentRepository.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/comment/service/CommentService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/controller/FeedController.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/dto/FeedRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/dto/FeedResponse.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/dto/UpdateFeedRequest.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/entity/Feed.kt
  src/main/kotlin/team/springpsring/petpartner/domain/feed/service/FeedService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/love/entity/Love.kt
  src/main/kotlin/team/springpsring/petpartner/domain/love/repository/LoveRepository.kt
  src/main/kotlin/team/springpsring/petpartner/domain/love/service/LoveService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/controller/UserController.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/dto/UserResponse.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/loginUser/service/LoginUserService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/service/UserService.kt
  src/main/kotlin/team/springpsring/petpartner/domain/user/validemail/service/ValidEmailService.kt
Labels: ♻Refactor
